name: siparislio
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get:
  connectivity_plus: ^5.0.2
  lottie: ^3.1.0
  url_launcher: ^6.2.6
  permission_handler: ^11.3.1
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  webview_flutter: ^4.7.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  firebase_analytics: ^10.10.5
  upgrader: ^10.3.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
flutter_native_splash:
  image: "assets/icon/logo_trans.png"
  color: "#1C182F"
flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/json/
