// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1kGKi6sHB2qkCYpc0w7LIm-kWNDrahxc',
    appId: '1:1044953230099:web:e02deee4d1d813919988e6',
    messagingSenderId: '1044953230099',
    projectId: 'siparislio-eaeea',
    authDomain: 'siparislio-eaeea.firebaseapp.com',
    storageBucket: 'siparislio-eaeea.appspot.com',
    measurementId: 'G-G4BX391DHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVXOOGtj57K7s81mhZnSHA24OK0ftyeP4',
    appId: '1:1044953230099:android:7dff20bd7af3d8e99988e6',
    messagingSenderId: '1044953230099',
    projectId: 'siparislio-eaeea',
    storageBucket: 'siparislio-eaeea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyGmhoEuyxhhHfJx0G1B0J8NN0tdz7pMU',
    appId: '1:1044953230099:ios:4c98d5c5e8e9fab29988e6',
    messagingSenderId: '1044953230099',
    projectId: 'siparislio-eaeea',
    storageBucket: 'siparislio-eaeea.appspot.com',
    iosBundleId: 'com.siparislio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlLFqc7zL1CPdXJZNURK7nMtgB6IyZ1VI',
    appId: '1:1020765281666:ios:ade0dbca7a9480441c439b',
    messagingSenderId: '1020765281666',
    projectId: 'siparislio-4d7c6',
    storageBucket: 'siparislio-4d7c6.appspot.com',
    iosBundleId: 'com.siparislio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByoqkERPs5toATJq0HrFoRDM87qFIQE3g',
    appId: '1:1020765281666:web:230dc4c5fee2e4121c439b',
    messagingSenderId: '1020765281666',
    projectId: 'siparislio-4d7c6',
    authDomain: 'siparislio-4d7c6.firebaseapp.com',
    storageBucket: 'siparislio-4d7c6.appspot.com',
    measurementId: 'G-JWMHS9VN9L',
  );
}